version: "3.9"
services:
  php-fpm:
    container_name: ${APP_NAME}-php-fpm
    build: ./infra/php
    volumes:
      - ./backend:/work
    expose:
      - 9000
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:1.20-alpine
    ports:
      - "3000:80"
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./infra/mysql/volumes:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - "8080:80"
